### ISSUE TITLE
Copyright update to 2016

### ISSUE THREAD

**Issue by mrb113** [hacsoc/hacsoc.github.com#20]
I don't have a way to test this so I don't want to send a pull request and ruin your website, but what you can do instead of just putting "Copyright 2015" and needing to update it every year is this:

```
<div id="copyright">
            <footer class="inner">
                <p>&copy;
                    <script type="text/javascript">
                    var d = new Date();
                    document.write(d.getFullYear());
                    </script> Hacker Society</p>
            </footer>
        </div>
```

(can probably make that shorter but I'm rubbish at javascript)

which should come out like © 2016 Hacker Society

**Comment by mrb113** [comment]
test it to be sure though :)

**Comment by ajm188** [comment]
What about people with `<noscript>`?

**Comment by mrb113** [comment]
can probs add a generic copyright line between noscript tags. or just not use the auto javascript and manually put it to 2016

**Comment by ajm188** [comment]
I'm fine with either of those two options

**Comment by ajm188** [comment]
@mrb113 I'm gonna close this unless you'd like to give it another go
